<?php
/*
 * @package    Loom_SizeChart
 * @copyright  Loom Oy - 2019
 */

// @codingStandardsIgnoreFile

?>

<?php
//$_helper = $this->helper('Magento\Catalog\Helper\Output');
$product = $block->getProduct();
$manufacturer = $product->getResource()->getAttribute('manufacturer')->getFrontend()->getValue($product);
$gender = $product->getResource()->getAttribute('gender')->getFrontend()->getValue($product);
?>
    <div class="sizechart-wrapper">
        <a href="#" id="sizechart-link">
            <span><img class="measure_icon" src="<?php echo $this->getViewFileUrl('Loom_SizeChart::images/sizechart_icon.png'); ?>" /></span>
            <span class="chart_text"><?php echo __('Sizechart'); ?></span>
        </a>
    </div>
    <div id="sizechart-modal" style="display:none;">
        <?php if (strstr($gender, 'Unisex')) { ?>
            <br />
            <span><h2><?php echo __('Men'); ?></h2></span>
            <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')
            ->setBlockId('sizechart_' . strtolower($manufacturer) . '_' . 'miehet')->toHtml(); ?>
            <div style="border-top: 3px dashed black;"><br /></div>
            <span><h2><?php echo __('Women'); ?></h2></span>
            <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')
            ->setBlockId('sizechart_' . strtolower($manufacturer) . '_' . 'naiset')->toHtml();
        } else {
        echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')
            ->setBlockId('sizechart_' . strtolower($manufacturer) . '_' . strtolower($gender))->toHtml();
        } ?>
    </div>

<script>
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal',
            'mage/translate'
        ],
        function(
            $,
            modal
        ) {
            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: false,
                title: 'Kokotaulukko',
                buttons: [{
                    text: $.mage.__('Sulje'),
                    class: '',
                    click: function () {
                        this.closeModal();
                    }
                }]
            };

            var popup = modal(options, $('#sizechart-modal'));

            $("#sizechart-link").on('click',function(){
                $("#sizechart-modal").modal("openModal");
            });
        }
    );
</script>
