<?php
/**
 * Blog recent posts widget
 *
 * @var $block \Magefan\Blog\Block\Widget\Recent
 */
?>

<?php
    $_postCollection = $block->getPostCollection();
?>
<?php if ($_postCollection->count()) { ?>
<div class="post-list-wrapper blog-widget-recent">
    <h3 style="color: #fff;" class="title"><?php echo $block->escapeHtml($block->getTitle()) ?></h3>
    <ul class="post-list clearfix">
        <?php foreach ($_postCollection as $_post) { ?>
            <?php
                $_postUrl = $_post->getPostUrl();
                $_postName = $block->escapeHtml($_post->getTitle(), null, true);
            ?>
            <li class="post-holder post-holder-<?php echo $_post->getId() ?>">
                <div class="post-header">

                    <div class="post-date">
                        <span class="value"><?php echo $_post->getPublishDate('d.m.Y') ?></span>
                    </div>
                    <div class="post-title-holder clearfix">
                        <div class="post-title">
                            <a class="post-item-link" style="display: block ruby;"
                               href="<?php echo $_postUrl ?>">
                                <h2><?php echo $_postName; ?></h2>
                            </a>
                        </div>
                    </div>
                </div>

                <div class="post-content">
                    <div class="post-description clearfix">
                        <?php if ($featuredImage = $_post->getFeaturedImage()) { ?>
                        <div class="post-ftimg-hld">
                            <a href="<?php echo $_postUrl ?>" title="<?php echo $_postName ?>">
                                <img src="<?php echo $featuredImage ?>" alt="<?php echo $_postName ?>" />
                            </a>
                        </div>
                        <?php } ?>
                        <div class="post-text-hld clearfix">
                            <?php echo $block->getShorContent($_post) ?>
                        </div>
                        <a class="post-read-more" href="<?php echo $_postUrl ?>" title="<?php echo $_postName ?>">
                           <?php echo __('Read more') ?>
                        </a>
                    </div>
                </div>
                <div class="post-footer">

                </div>
            </li>

        <?php } ?>
    </ul>
</div>
<?php } ?>